apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxgwy4189-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxgwy4189-tenant-component
    app.kubernetes.io/part-of: loadxgwy4189-tenant-app
  name: loadxgwy4189-tenant-component
  namespace: loadxgwy4189-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxgwy4189-tenant-component
    weight: null
status: {}
