apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxgwy4189-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxgwy4189-tenant-component
    app.kubernetes.io/part-of: loadxgwy4189-tenant-app
  name: loadxgwy4189-tenant-component
  namespace: loadxgwy4189-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadxgwy4189-tenant-component
status:
  loadBalancer: {}
